export const SOCKET_EVENTS = Object.freeze({
  JOIN: 'join',
  REQUEST_PUBLIC: 'requestPublic',
  MESSAGE: 'message',
  DELETE_LISTING: 'deleteListing',
  REQUEST_RSA: 'RequestRSA',
  SERVER_RSA: 'ServerRSA',
  CLIENT_AES_KEY: 'ClientAESKey',
  GIVE_MATCHES: 'Give Matches',
  NEW_MATCHES: 'New Matches',
  CREATE_USER: 'Create User',
  USER_EXISTS: 'User Exists',
  USER_NOT_EXIST: 'User Not Exist',
  REMOVE_HOBBIES: 'Remove Hobbies',
  GIVE_HOBBIES: 'Give Hobbies',
  REMOVE_MODULES: 'Remove Modules',
  GIVE_MODULES: 'Give Modules',
  ADD_HOBBIES: 'Add Hobbies',
  ADD_MODULES: 'Add Modules',
  REMOVE_IMAGE: 'Remove Image',
  IMAGE_REMOVED: 'Image Removed',
  HIGHLIGHT_USER: 'Highlight User',
  SKIP_USER: 'Skip User',
  UPDATE_BIOGRAPHY: 'Update Biography',
  GIVE_BIOGRAPHY: 'Give Biography',
  UPDATE_HOBBIES: 'Update Hobbies',
  UPDATE_MODULES: 'Update Modules',
  SET_REVISING: 'Set Revising',
  GET_REVISING: 'Get Revising',
  CURRENTLY_REVISING: 'currently Revising',
  GET_BIOGRAPHY: 'Get Biography',
  GET_HOBBIES: 'Get Hobbies',
  GET_MODULES: 'Get Modules',
  CHECK_CONVERSATION: 'checkConversation',
  NEW_MESSAGES: 'New Messages',
  SEND_MESSAGE: 'sendMessage',
  CHECK_EMAIL: 'checkEmail',
  TEST_AUTH: 'test Auth',
});

export const PROFILE_ENTRY_TYPES = Object.freeze({
  HOBBIES: 'hobbys',
  MODULES: 'modules',
  IMAGES: 'images',
});

export const DEFAULT_REVISITING_STATUS = 'Not Currently Revising';
